-- AlterTable
ALTER TABLE "BalanceYear" ADD COLUMN     "ratioDio" DOUBLE PRECISION,
ADD COLUMN     "ratioDpo" DOUBLE PRECISION,
ADD COLUMN     "ratioDso" DOUBLE PRECISION,
ADD COLUMN     "ratioOcaPct" DOUBLE PRECISION,
ADD COLUMN     "ratioOclPct" DOUBLE PRECISION;
