-- AlterTable
ALTER TABLE "BalanceYear" ADD COLUMN     "otherShortTermAssets" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otherShortTermLiabilities" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "payables" DOUBLE PRECISION NOT NULL DEFAULT 0;
